version: '2'
services:
    submission:
        build: .
        image: kaggle_submission_tracker:1.0.0
        environment:
        - PORT=9090
        ports:
        - "9090:9090"
    nginx:
        image: "nginx:1.11.9"
        ports:
        - "8080:80"
        links:
        - submission